name: anime_world_tutorial
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  crystal_navigation_bar: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  gap: ^3.0.1
  http: ^1.2.1
  iconly: ^1.0.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: anime
      fonts:
        - asset: assets/fonts/anime-ace.regular.ttf

    - family: Jujutsu
      fonts:
        - asset: assets/fonts/Jujutsu Kaisen.ttf

    - family: manga
      fonts:
        - asset: assets/fonts/manga-temple.regular.ttf
