name: anime_world_tutorial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Image Slider
  carousel_slider: ^4.2.1

  # Dot indicator
  smooth_page_indicator: ^1.1.0

  # managing state
  flutter_bloc: ^8.1.3

  # making api calls
  http: ^1.2.0

  # storing preferences locally
  shared_preferences: ^2.2.2

  # caching images for faster loading
  cached_network_image: ^3.3.1

  # animes staggered view
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
